---
title: "STM_Model"
output: html_document
date: "2023-12-14"
---

```{r}

library(stm)
setwd("/Users/aniruddhbhaskaran/Documents/RA-DMHE")

```

```{r}

data <- read.csv("descriptions.csv")
data

```


```{r}

processed <- textProcessor(data$short_description, metadata = data, stem = FALSE)
processed

```
```{r}

out <- prepDocuments(processed$documents, processed$vocab, processed$meta)

```

```{r}

docs <- out$documents
vocab <- out$vocab
meta <- out$meta

# z <- data$short_description[-out$docs.removed]

```

```{r}

plotRemoved(processed$documents, lower.thresh = seq(1, 200, by=100))

```

```{r}

modelPrevFit <- stm(documents = out$documents, vocab = out$vocab, K = 20, prevalence =~ country_code + dummy_mental_health + s(founded_year),
                    , data = out$meta, init.type = "Spectral")

```

```{r}

modelTest2 <- stm(documents = out$documents, vocab = out$vocab, K = 0, prevalence =~ country_code + dummy_mental_health + s(founded_year),
                    , data = out$meta, init.type = "Spectral")

```

```{r}

labelTopics(modelPrevFit, c(1, 2, 3))

```

```{r}

# modelPrevFit2 <- stm(documents = out$documents, vocab = out$vocab, K = 40, prevalence =~ country_code + dummy_mental_health + s(founded_year),
#                     , data = out$meta, init.type = "Spectral")

```

```{r}

labelTopics(modelPrevFit, c(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20))

```

```{r}

shortdoc <- substr(out$meta$short_description, 1, 200)
thoughts15 <- findThoughts(modelPrevFit, texts=shortdoc, n=10, topics = 15)$docs[[1]]
par(mfrow = c(1, 1), mar = c(1, 1, 1, 1))
plotQuote(thoughts15, width=400, main="Topic 15")

```
```{r}

typeof(thoughts1)

```

```{r}

topicNames <- c("Topic 1: Physical and Mental Therapy", "Topic 2: Gene Therapy", "Topic 3: Personal Wellbeing and Fitness",
                "Topic 4: Life Sciences and Social Services", "Topic 5: Healthcare Communications Platforms", 
                "Topic 6: Substance Abuse Treatment", "Topic 7: Product and Business Research & Development",
                "Topic 8: Healthcare Information Technology", "Topic 9: Healthcare Engineering and Robotics",
                "Topic 10: Electronic Medical Records Management", "Topic 11: Biometric Authentication Technology",
                "Topic 12: Social Care and Assisted Living Services", "Topic 13: ML and AI Diagnostics",
                "Topic 14: Healthcare Consulting", "Topic 15: Mental Healthcare Services",
                "Topic 16: Healthcare Mobile App Developers", "Topic 17: Healthcare Data Saas Platform Developers",
                "Topic 18: Pharmaceutical and Chemical Research & Development", "Topic 19: Dental Products and Services",
                "Topic 20: Healthcare Logistics Tools")

# tiff(file="topicPlot3.tiff", units="in", width=9, height=5, res = 300)
plot(modelPrevFit, type="summary", xlim=c(0, 0.3), custom.labels = "", topic.names = topicNames)
# dev.off()


```

```{r}

library("dplyr")

prop_table <- make.dt(modelPrevFit)

summarise_all(prop_table, mean)

```

```{r}

out$meta$dummy_mental_health <- as.factor(out$meta$dummy_mental_health)

prep <- estimateEffect(1:20 ~ country_code + dummy_mental_health + s(founded_year), modelPrevFit, meta=out$meta, uncertainty = "Global")

summary(prep, topics = 15)

```

```{r}

tiff(file="marginalTopicPlot.tiff", units="in", width=9, height=5, res = 300)
plot(prep, covariate = "dummy_mental_health", topics = c(1, 3, 15), model = modelPrevFit, method = "pointestimate", xlim = c(-0.05, 0.1), labeltype = "custom", custom.labels = c("Physical and Mental Therapy (DMH: 0)", "Personal Well-being and Fitness (DMH: 0)", "Mental Healthcare Services (DMH: 0)", "Physical and Mental Therapy (DMH: 1)", "Personal Well-being and Fitness (DMH: 1)", "Mental Healthcare Services (DMH: 1)"))
dev.off()


```
```{r}

plot(prep, covariate = "country_code", topics = c(1, 3, 15), model = modelPrevFit, method = "pointestimate", xlim = c(-0.05, 0.1))

```

```{r}


plot(prep, covariate = "founded_year", method = "continuous", topics = 15, model = modelPrevFit)

```

```{r}

plot(prep, covariate = "founded_year", method = "continuous", topics = 3, model = modelPrevFit, xlim = c(1995, 2022))


```

```{r}

# tiff(file="topic15Plot.tiff", units="in", width=9, height=5, res = 300)
plot(prep, covariate = "founded_year", method = "continuous", topics = 15, model = modelPrevFit, xlim = c(1995, 2022), printlegend = FALSE, linecol = "darkgreen")
legend("topleft", legend="Topic 15: Mental Healthcare Services", lty = 1:2, col = "darkgreen")
# dev.off()

```


```{r}

tiff(file="topic15cloud.tiff", units="in", width=9, height=5, res = 300)
cloud(modelPrevFit, topic = 15, scale = c(2, 0.5))
dev.off()

```
```{r}

library(igraph)
mod.out.corr <- topicCorr(modelPrevFit)
plot(mod.out.corr)

```

